server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis   # 👈 antes decía 'simple'
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,beans"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.data.redis: INFO
